In [1]:
import os
from prerender.utils.features_description import *
import tensorflow as tf

2023-04-20 01:03:27.811039: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
project_dir = "/Users/xuyixuan/Downloads/Project/waymo-motion-prediction-challenge-2022-multipath-plus-plus"
FILENAME = os.path.join(project_dir, 'dataset/tfrecord-00004-of-01000')


In [3]:
dataset = tf.data.TFRecordDataset(FILENAME, compression_type='')
data = next(dataset.as_numpy_iterator())

2023-04-20 01:03:32.044929: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
features_description = generate_features_description()

In [5]:
data

In [6]:
parsed = tf.io.parse_single_example(data, features_description)
parsed

{'roadgraph_samples/dir': <tf.Tensor: shape=(30000, 3), dtype=float32, numpy=
 array([[ 0.02333741,  0.9997066 ,  0.00648669],
        [ 0.02338673,  0.99970543,  0.00648669],
        [ 0.02342151,  0.99970466,  0.00648669],
        ...,
        [-1.        , -1.        , -1.        ],
        [-1.        , -1.        , -1.        ],
        [-1.        , -1.        , -1.        ]], dtype=float32)>,
 'roadgraph_samples/id': <tf.Tensor: shape=(30000, 1), dtype=int64, numpy=
 array([[104],
        [104],
        [104],
        ...,
        [ -1],
        [ -1],
        [ -1]])>,
 'roadgraph_samples/type': <tf.Tensor: shape=(30000, 1), dtype=int64, numpy=
 array([[ 2],
        [ 2],
        [ 2],
        ...,
        [-1],
        [-1],
        [-1]])>,
 'roadgraph_samples/valid': <tf.Tensor: shape=(30000, 1), dtype=int64, numpy=
 array([[1],
        [1],
        [1],
        ...,
        [0],
        [0],
        [0]])>,
 'roadgraph_samples/xyz': <tf.Tensor: shape=(30000, 3), dtype=float